### ISSUE TITLE
Te rog sterge linia respectiva ca nu are sens, o sa-ti mai las feedback

### ISSUE THREAD

**Issue by MariusDK** [Gratian95/facebook-clone---only-HTML-and-CSS#1]
https://github.com/Gratian95/facebook-clone---only-HTML-and-CSS/blob/564e59376651904fdf91b5f56f3ee38d90c2ec1c/facebook%20clone.html#L12

There is no logic in using max-height none

**Comment by Gratian95** [comment]
I checked the code and, indeed, you are right, there is no use there for max-height:none. Thank you for your feedback!
